name: ci-python
on:
  pull_request:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install uv
        run: pip install uv

      - name: Resolve & install (apps/api)
        working-directory: apps/api
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -e ".[dev]"
      - name: Lint (ruff)
        working-directory: apps/api
        run: |
          source .venv/bin/activate
          ruff check app tests
      - name: Tests (pytest)
        working-directory: apps/api
        run: |
          source .venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q
      - name: Build (PEP 517)
        working-directory: apps/api
        run: |
          source .venv/bin/activate
          python -m build
