name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate tag matches VERSION
        run: |
          TAG="${GITHUB_REF_NAME}"
          FILE_VER=$(cat VERSION)
          if [ "$TAG" != "v${FILE_VER}" ]; then
            echo "Tag ($TAG) must match VERSION (v${FILE_VER})" >&2
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.5'

      - name: Install build tooling
        run: pip install uv build

      - name: Build backend artifacts
        working-directory: backend
        run: |
          uv venv .venv
          source .venv/bin/activate
          python -m build

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            backend/dist/*

